/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onelibraryversion2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author hp
 */
public class Page5 extends javax.swing.JFrame {

    /**
     * Creates new form Page5
     */SimpleDateFormat s2;
    Date d1;
    public Page5() {
        initComponents();
    
            new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                d1 = new Date();
                s2 = new SimpleDateFormat("dd-MM-YYYY hh-mm-ss a");
                jTextField7.setText(s2.format(d1));

            }
        }
        ).start();
        FillBox();
    }

     private void FillBox() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            Statement st1 = con1.createStatement();
            ResultSet re1 = st1.executeQuery("select * from AddBooks");
            int r = 1;
            while (re1.next()) {
                String name1 = re1.getString(2);
                jComboBox1.addItem(name1);
                
//                Image image = (Image) piop;
//                iop = (Icon) image;
            }
            re1.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
     String bookname;
    void fetch(){
             try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            Statement st1 = con1.createStatement();
            ResultSet re1 = st1.executeQuery("select * from addbooks");
            int r = 1;
            while (r != 0) {
                re1.next();
                bookname = re1.getString(2);
                
            }
            re1.close();
            JOptionPane.showMessageDialog(null, "Query Executed");
        } catch (Exception qe) {

        }
    }
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(940, 30, 20, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(570, 60, 380, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(570, 130, 380, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(570, 200, 380, 40);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(570, 270, 380, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(570, 340, 380, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(570, 410, 380, 40);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(570, 480, 380, 40);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(570, 550, 380, 40);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 620, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Page5_5.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1088, 670);

        setSize(new java.awt.Dimension(1088, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String s_name = jTextField1.getText().toString();
        String s_roll = jTextField2.getText().toString();
        String s_branch = jTextField3.getText().toString();
        
        String b_id = jTextField5.getText().toString();
        String b_author = jTextField4.getText().toString();
        String b_entry = jTextField6.getText().toString();
        String b_today = jTextField7.getText().toString();
 try {
            theQuery("insert into Addborrower(student_name,student_roll,student_branch,bookid,bookname,bookauthorname,entrydate,renttime) values('"
                    + s_name + "','"
                    + s_roll + "','"
                    + s_branch + "','"
                    + b_id + "','"
                    + b_name + "','"
                    + b_author + "','"
                    + b_entry + "','"
                    
                    + s2.format(d1) + "')"
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked
String b_name;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 b_name = jComboBox1.getSelectedItem().toString();

        try {
            //            jLabel1.setText("Connecting Network......");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            Statement st1 = con1.createStatement();
            ResultSet re1 = st1.executeQuery("select * from AddBooks WHERE bookname = '" + b_name + "'");
            //            jLabel1.setText("Connection Stablished...");
            int r = 1;
            while (r != 0) {
                re1.next();
                r = re1.getString(1).compareToIgnoreCase(b_name);

                //                getContentPane().add(img123);
                String bookid  = re1.getString(1);
                String bookname = re1.getString(2);
                String author = re1.getString(3);
                String entry = re1.getString(4);
                jTextField4.setText(author);
                jTextField5.setText(bookid);
                jTextField6.setText(entry);
                //                jLabel1.setText("Customer Detail Found");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */PreparedStatement ps;
    Connection con = null;
    Statement st = null;
    ResultSet re = null;
    public void theQuery(String query) {

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Done Successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
