/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onelibraryversion2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Page4 extends javax.swing.JFrame {
 String bookname;
    /**
     * Creates new form Page4
     */
    public Page4() {
        initComponents();
        
    FillBox();
    }
     private void FillBox() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            Statement st1 = con1.createStatement();
            ResultSet re1 = st1.executeQuery("select * from AddBooks");
            int r = 1;
            while (re1.next()) {
                String name1 = re1.getString(2);
                jComboBox1.addItem(name1);
                
//                Image image = (Image) piop;
//                iop = (Icon) image;
            }
            re1.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    void fetch(){
             try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            Statement st1 = con1.createStatement();
            ResultSet re1 = st1.executeQuery("select * from addbooks");
            int r = 1;
            while (r != 0) {
                re1.next();
                bookname = re1.getString(2);
                
            }
            re1.close();
            JOptionPane.showMessageDialog(null, "Query Executed");
        } catch (Exception qe) {

        }
    }    
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(940, 30, 20, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(420, 270, 380, 40);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(420, 340, 380, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(420, 410, 380, 40);

        jComboBox1.setBackground(new java.awt.Color(166, 27, 32));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(420, 200, 380, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Page4_4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1092, 670);

        setSize(new java.awt.Dimension(1092, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked
String a;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   a = jComboBox1.getSelectedItem().toString();
       

        try {
//            jLabel1.setText("Connecting Network......");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library", "root", "kunal");
            Statement st1 = con1.createStatement();
            ResultSet re1 = st1.executeQuery("select * from AddBooks WHERE bookname = '" + a + "'");
//            jLabel1.setText("Connection Stablished...");
            int r = 1;
            while (r != 0) {
                re1.next();
                 r = re1.getString(1).compareToIgnoreCase(a);
                
//                getContentPane().add(img123);
                String bookid  = re1.getString(1);
                String bookname = re1.getString(2);
                String author = re1.getString(3);
                String entry = re1.getString(4);
                jTextField2.setText(author);
                jTextField3.setText(bookid);
                jTextField4.setText(entry);
//                jLabel1.setText("Customer Detail Found");
            }
        
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
